### ISSUE TITLE
Wascally doesn't work with the node 'config' module installed

### ISSUE THREAD

**Issue by xiehan** [LeanKit-Labs/wascally#64]
I'm setting up a new project and tried to just get Wascally working with the pub/sub demo code. Was stumped for hours on some mysterious errors. Turns out it was all because I was trying to use the node [config](https://github.com/lorenwest/node-config) module; once I hard-coded my configuration settings into the js file and uninstalled the config module, the demo code ran just fine.

I'm hoping this is not too difficult to fix, because it's kind of a deal-breaker for us. :disappointed: 

```
Error: Configuration property "RABBIT_BROKER" is not defined
    at Object.Config.get (./node_modules/config/lib/config.js:177:11)
    at getOption (./node_modules/wascally/src/amqp/connection.js:11:15)
    at new Adapter (./node_modules/wascally/src/amqp/connection.js:38:19)
    at module.exports (./node_modules/wascally/src/amqp/connection.js:141:16)
    at machina.Fsm.extend.states.initializing._onEnter (./node_modules/wascally/src/connectionFsm.js:75:19)
    at _.extend.transition (./node_modules/wascally/node_modules/machina/lib/machina.js:200:56)
    at Fsm (./node_modules/wascally/node_modules/machina/lib/machina.js:111:18)
    at new fsm (./node_modules/wascally/node_modules/machina/lib/machina.js:330:24)
    at Connection (./node_modules/wascally/src/connectionFsm.js:186:9)
    at Broker.addConnection (./node_modules/wascally/src/index.js:35:20)

TypeError: Cannot read property 'channels' of undefined
    at Broker.getExchange (./node_modules/wascally/src/index.js:126:43)
    at bound [as getExchange] (./node_modules/wascally/node_modules/lodash/dist/lodash.js:729:21)
    at Broker.publish (./node_modules/wascally/src/index.js:187:14)
    at bound [as publish] (./node_modules/wascally/node_modules/lodash/dist/lodash.js:729:21)
    at null.<anonymous> (./node_modules/wascally/src/index.js:205:8)
    at runResolver (./node_modules/wascally/node_modules/when/lib/makePromise.js:59:5)
    at new Promise (./node_modules/wascally/node_modules/when/lib/makePromise.js:30:4)
    at Function.promise (./node_modules/wascally/node_modules/when/when.js:87:10)
    at Broker.request (./node_modules/wascally/src/index.js:196:14)
    at bound [as request] (./node_modules/wascally/node_modules/lodash/dist/lodash.js:729:21)
```

**Comment by mehcode** [comment]
@xiehan We're using wascally with node-config and its working fine.

```js
// [...] from our config/default.js
  mediator: {
    // Force all events to be invoked in the loop rather than
    // deferred to the message queue
    // NOTE: Inteded for a testing environment
    eager: false,

    // Connection information for the message broker (RabbitMQ).
    broker: {
      user: "guest",
      password: "guest",
      host: "localhost",
      port: 5672,
    }
  },
```

Perhaps your usage of node-config is wrong?

```js
// snipped from our topology.js file
  return rabbit.configure({
    // Gather the broker connection information
    connection: {
      user: config.get("mediator.broker.user"),
      pass: config.get("mediator.broker.password"),
      server: [config.get("mediator.broker.host")],
      port: config.get("mediator.broker.port"),
      vhost: "%2f",
      replyQueue: false,
    },
  // [...]
});
```

**Comment by xiehan** [comment]
It doesn't take rocket science to use node-config, so unless I am missing something huge, there's something else going on. I'm willing to accept that it might be more of a bug (or at least undocumented/unintended behavior) in node-config rather than in wascally. Here is where I landed after a bit more investigating.

---

First of all, just to recap, this works fine:

```javascript
// config.js - manual config file, not using node-config (quotes around keys are artifacts from copy/paste)
module.exports = {
    "workers": 8,
    "RabbitMQ": {
        "connection": {
            "user": "guest",
            "pass": "guest",
            "server": [
                "127.0.0.1"
            ],
            "port": 5672
        },
        "exchanges": [
            {
                "name": "wascally-pubsub-messages-x",
                ...
            },
            ...
        ],
        "queues": [
            {
                "name": "wascally-pubsub-messages-q",
                ...
            },
            ...
        ],
        "bindings": [
            {
                "exchange": "wascally-pubsub-messages-x",
                ...
            },
            ...
        ]
    }
};
```
```javascript
// topology.js
var config = require('./config.js');

var settings = {
    connection: config.RabbitMQ.connection,
    exchanges: config.RabbitMQ.exchanges,
    queues: config.RabbitMQ.queues,
    bindings: config.RabbitMQ.bindings
};
return rabbit.configure(settings).then(function () { ... });
```

Code runs just fine, results are as expected, no errors.

---

This is what I tried yesterday, and doesn't work:

```javascript
// config/default.json
{
    "workers": 8,
    "RabbitMQ": {
        "connection": {
            "user": "guest",
            "pass": "guest",
            "server": [
                "127.0.0.1"
            ],
            "port": 5672
        },
        "exchanges": [
            {
                "name": "wascally-pubsub-messages-x",
                ...
            },
            ...
        ],
        "queues": [
            {
                "name": "wascally-pubsub-messages-q",
                ...
            },
            ...
        ],
        "bindings": [
            {
                "exchange": "wascally-pubsub-messages-x",
                ...
            },
            ...
        ]
    }
}
```
```javascript
// topology.js
var config = require('config');

var settings = {
    connection: config.get('RabbitMQ.connection'),
    exchanges: config.get('RabbitMQ.exchanges'),
    queues: config.get('RabbitMQ.queues'),
    bindings: config.get('RabbitMQ.bindings')
};
return rabbit.configure(settings).then(function () { ... });
```

When run it yields:
```
Error: Configuration property "RABBIT_BROKER" is not defined
    at Object.Config.get (./node_modules/config/lib/config.js:177:11)
    at getOption (./node_modules/wascally/src/amqp/connection.js:11:15)
    at new Adapter (./node_modules/wascally/src/amqp/connection.js:38:19)
    at module.exports (./node_modules/wascally/src/amqp/connection.js:141:16)
    at machina.Fsm.extend.states.initializing._onEnter (./node_modules/wascally/src/connectionFsm.js:75:19)
    at _.extend.transition (./node_modules/wascally/node_modules/machina/lib/machina.js:200:56)
    at Fsm (./node_modules/wascally/node_modules/machina/lib/machina.js:111:18)
    at new fsm (./node_modules/wascally/node_modules/machina/lib/machina.js:330:24)
    at Connection (./node_modules/wascally/src/connectionFsm.js:186:9)
    at Broker.addConnection (./node_modules/wascally/src/index.js:35:20)
```

even though a `console.log` of the settings object looks as though you would expect:

```javascript
{ connection: 
   { user: 'guest',
     pass: 'guest',
     server: [ '127.0.0.1' ],
     port: 5672 },
  exchanges: 
   [ { name: 'wascally-pubsub-requests-x',
       type: 'direct',
       persistent: true },
     { name: 'wascally-pubsub-messages-x',
       type: 'direct',
       persistent: true } ],
  queues: 
   [ { name: 'wascally-pubsub-requests-q',
       persistent: true,
       noBatch: true,
       limit: 1 },
     { name: 'wascally-pubsub-messages-q',
       persistent: true,
       noBatch: true,
       limit: 1 } ],
  bindings: 
   [ { exchange: 'wascally-pubsub-requests-x',
       target: 'wascally-pubsub-requests-q',
       keys: [Object] },
     { exchange: 'wascally-pubsub-messages-x',
       target: 'wascally-pubsub-messages-q',
       keys: [] } ] }
```

---

So I dove into the node-config documentation to see if there was anything at all I could've missed, and found that they added a bunch of [utility functions](https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities) and so I gave one of those a whirl just to see what happens.

Now:

```javascript
// topology.js
var config = require('config');

var settings = config.util.extendDeep({}, config.get('RabbitMQ'));
return rabbit.configure(settings).then(function () { ... });
```

...works. Mysteriously, a `console.log` of the settings object is 100% identical to the one in the scenario above:

```javascript
{ connection: 
   { user: 'guest',
     pass: 'guest',
     server: [ '127.0.0.1' ],
     port: 5672 },
  exchanges: 
   [ { name: 'wascally-pubsub-requests-x',
       type: 'direct',
       persistent: true },
     { name: 'wascally-pubsub-messages-x',
       type: 'direct',
       persistent: true } ],
  queues: 
   [ { name: 'wascally-pubsub-requests-q',
       persistent: true,
       noBatch: true,
       limit: 1 },
     { name: 'wascally-pubsub-messages-q',
       persistent: true,
       noBatch: true,
       limit: 1 } ],
  bindings: 
   [ { exchange: 'wascally-pubsub-requests-x',
       target: 'wascally-pubsub-requests-q',
       keys: [Object] },
     { exchange: 'wascally-pubsub-messages-x',
       target: 'wascally-pubsub-messages-q',
       keys: [] } ] }
```

That would suggest there's something node-config is doing internally when the values are arrays that isn't playing nicely when passed over to wascally. I don't have time to debug it much more thoroughly than this (and since I found a solution -- using `config.util.extendDeep` -- I can't justify spending any more time on this -- my boss already isn't happy) but all the brief cursory tests I did to try to find the difference between my old way of creating the `settings` object vs. using `config.util.extendDeep` didn't reveal anything.

**Comment by FGRibreau** [comment]
Just a user-side feedback, at Bringr we use [common-env](https://github.com/FGRibreau/common-env) to allow configuration of every aspect of our default wascally topology.
